Page de connexion
DavalEnzo/file-storage pull request #7
Opened 2023-03-19 15:43 UTC by Moranoo

Page de connexion (reste à savoir sur quel page le diriger une fois connecter)

2023-03-20 16:19 UTC, DavalEnzo requested changes
Faudrait voir un peu comment tout est agencé avec une petite démo. Y'aurait peut être certaines choses a voir

2023-03-20 16:19 UTC, DavalEnzo commented on src/Entity/User.php
> +#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
```suggestion
#[UniqueEntity(fields: ['email'], message: 'Un compte est déjà lié à cet email')]
```

2023-03-20 16:19 UTC, DavalEnzo commented on src/Controller/IndexController.php
> +    public function new(Request $request,EntityManagerInterface $entityManager) : Response
Traitement de la connexion dans le controller index ?? Normalement on a un login controller

2023-03-20 16:19 UTC, DavalEnzo commented on templates/base.html.twig
> +        <title>{% block title %}Bienvenu FileStorage{% endblock %}</title>
```suggestion
        <title>{% block title %}Accueil FileStorage{% endblock %}</title>
```

2023-03-20 16:57 UTC, Moranoo commented on src/Controller/IndexController.php
> +    public function new(Request $request,EntityManagerInterface $entityManager) : Response
un controller pour chaque section 
je pensais que dans le index on placera les méthodes pour afficher le client une fois connecter

2023-03-21 10:13 UTC, DavalEnzo commented on src/Controller/IndexController.php
> +    public function new(Request $request,EntityManagerInterface $entityManager) : Response
Je pense qu'il est plus intéressant que l'index soit une page d'accueil et qu'il n'y ait que de l'affichage dessus. Pas de formulaires, pas de traitement. On pourra éventuellement modifier sa présentation avec twig lorsqu'un utilisateur sera connecté

2023-03-21 10:18 UTC, DavalEnzo approved these changes

2023-03-21 10:18 UTC, merged